#!/usr/bin/env ruby 

###############

#Project Euler Problem 2

# Question #
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

###############

@train = [0,1]

def fib set 

	return puts "Fibonacci Result of #{set} sets is #{@train[1]}" unless set > 1;
		set.times do 
			next_num = @train[0] + @train[1]
			@train.push(next_num).shift
		end
		return puts "Fibonacci Result of #{set} sets is #{@train[1]}"
end 



